Annotated Bibliography of useful books
========================================================

###   Thinking Fast and Slow

This is a book about recognizing your biases. 


Conclusion

#### Two Systems
* Concepts
Kaheman 
  * System 1: System 1 is the Haire. This is the automatic process in our mind that makes quick judgments and assessments--hence thinking fast. System 1 holds a model  of the world that is housed in our memory it parses out what is surprising and what is normal and establishes a causal relationship in seconds. This is where skill is housed through practice why intuition is going to work most of the time. However, system 1 is prone to bias.  Page 416 has a useful summary of - but is prone to bias. This makes sense from an evolutionary standpoint. 
  
  * System 2: System is the toruisue. This is metaphoric process that takes time to make close to rational decisions; it slows things down. 
  

  
#### A. Two Selves (Conclusion )
  * Concepts
    * Remembering Self
    * Experiencing self
    * Duration Neglect
    * Peak End Rule
    
*Important Point.     
"The neglect of duration combined with the peak-end rule causes a bias that favors a short period of intense joy over a long period moderate happiness" page 409. 

The inverse is also true people generally fear intense short term pain then deal with moderate long term pain.

3. What is evidence
    
2. Application

Can we alter this bias or just being aware of the bias sufficient as practical advice. 


#### B. Econs and Humans.

1. Concepts
  * Reasonable vs. Rationality
A reasonable person is one who is more less in touch with reality and is open to reasonable argument. A rational person is one who is consistent in their beliefs to the nth degree--it requires compliance with the rules of logic that is not realistic. 
  * Humans
  * Econs
  * Libertarian Paternalism
  * The book *Nudge*

Comment: I have always maintained that people are not rationale.

Kahneman notes that he dislikes that other sometimes claims that his work demonstrates that humans may be irrational. That is not the argument; the argument is that humans don't fit the rational model. 


Humans need assistance to make more astute judgments and author points that this is controversial among Chicago School of Economics and libertarians. The Libertarian idea that people should be free to choose so long as it does not hurt other people. 

####          Law of Small Numbers

1. Concepts
  * Large samples are more precise than small samples page 113
  * Small samples yield extreme results more often than large samples do. page 113. 
  * Smaller sample sizes yield more extreme results. 
  Code in Marble Example. 
  * "People are not adequately sensitive to sample size" p114
  * The reliability of the message is secondary to the content of the message.  
  

We are not comfortable with randomness; we seek to make patterns when in fact; "..A collection of random  events do behave in a highly regular fashion"" page 110. "

Comment: There is a lot of talk about randomness; does this discredit his own studies that he cites; it's just random. --Controlled experiments is most likely my answer. 

### Tom W's Speciality

* Sins of Representativeness: O
  1. One example is giving to much weight to representativensss in low base rate situations.
  
* System 1 will automatically process the information available as if it is true. There is one thing you can do when you have doubts about the quality of the evidence. Let your judgments of probability stay close to the base rate p.153. 


### Regression to the Mean

When our attention is called to an event our associate memory will look for a cause. activation will automatically spread to any cause that is already stored in memory 

Humans have a hard time with regression it took Galton. 
When the correlation between two measures is less than perfect, there will be regression to the mean.  p 180. 

p182. regression to the mean has an explanation but does not have a cause. 

My comment: So that is the point of the regression line. 
ha there I go looking for a story or pattern. 




========================================================
*Outliers*

### First Thoughts

1. Duh
2. Sociological Imagination.
3. Startling that there needs to be a balance between independence and guidance. 
4. You can correlate anything is this the case. 

=====================================================================

*Lila: An Inquiry Into Morals*

Robert M. Pirsig

The author of *Zen and the Art of Motorcycle Maintaince"

Discussing in more detail the Metaphyisc of Quality and the issues of subject matter philosophy. 


This book touches on key concepts in Anthropology, the social construction of mental illness, and the relationships between  Native Americans and Europeans.


A premise of the book is that there are two types of quality, static and dynamic. Static quality is the taken for granted basis of quality and dynamic quality is the unseen that allows for change and growth-evolution. 

* inorganic

* biological

* social

* intellectual

Biological value patterns consists of sex, eating, patterns that keep us alive and reproduce the species, and also tribalism. Social value patterns may suppress biological value patterns but in the long run are beneficial for society. It is beneficial for a more stability not to have sex with everyone whenever you fee like it. Intellectual value patterns are of a high order than social value patterns.

At times these value conflict with each other. That is where the concept of morals come into play within this book. 

This book gives a useful framework for understanding politics in 2016. Conservative republicans have argued that the reason for America's problems is the lack of social morals--too much sex, and freedom to do what ever you want. Social conservatives seem to value social value patterns over intellectual value patterns. This year the Republicans have turned to Donald Trump and seem to be regressing to valuing biological value patterns over social value patterns. There is some element to this but I think some are getting carried away with the celebrity aspect of politics. 

Key takeaway at the end of the book is Good is not an adjective but a noun. G

### Great Quotes

* "Take Care of your Goodness"* p.467 Dakota 

* "Good is a noun"* p.468

* "Karma is the pain and suffering that results from clinging to the static patterns of the world"*  p. 455

* While living be a dead man, be completely dead, and then do as you please, and all will be well* p. 454. 


### Key Concepts:

* Inorganic Value Patters*

*Biological Value Patterns*

*Social Value Patterns*

*Interllectual Value Patterns*


### Supporting Material:


[MOQ Website]("http://robertpirsig.org/Intro.html")

[NPR Interview-1974]("https://www.youtube.com/watch?v=RULOIr4MJII")

[BBC Interview]("https://www.youtube.com/watch?v=m8zdT5jYlro")


=================================================================

*Zen and the Art of Motorcycle Mainteance*
(https://youtu.be/0Bo3qaJIZUQ)